language: node_js
node_js:
  - "11.12.0"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  local-dir: ./dir
  provider: pages
  target-branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  on:
    branch: release